import { Group, Period, Program, Subject, UserPreference } from '../types';

export const MOCK_PROGRAMS: Program[] = [
  {
    id: 1,
    codigo: 'ING-SISTEMAS',
    nombre: 'Ingeniería de Sistemas',
    universidad: 'Universidad Popular del Cesar',
    activo: true,
  }
];

export const MOCK_PERIODS: Period[] = [
  {
    id: 1,
    nombre: '2026-2',
    fechaInicio: '2026-08-03',
    fechaFin: '2026-12-15',
    activo: true,
  }
];

// Asignaturas de Ingeniería de Sistemas UPC (Semestres 2 al 10)
// NOTA: Primer semestre excluido institucionalmente porque la UPC asigna horario cerrado.
export const MOCK_SUBJECTS: Subject[] = [
  // Semestre 2
  { id: 6, codigo: 'SS200', nombre: 'Programación de Computadores I', creditos: 3, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 5 },
  { id: 7, codigo: 'MT301B', nombre: 'Álgebra Lineal', creditos: 3, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 8, codigo: 'MT303B', nombre: 'Cálculo Integral', creditos: 4, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 9, codigo: 'FS202', nombre: 'Mecánica', creditos: 4, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 10, codigo: 'PG200', nombre: 'Comunicación Oral y Escrita II', creditos: 2, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 3 },

  // Semestre 3
  { id: 11, codigo: 'SS300', nombre: 'Programación de Computadores II', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 12, codigo: 'SS301', nombre: 'Estructura de Datos', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 13, codigo: 'MT331', nombre: 'Cálculo Multivariable', creditos: 4, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 14, codigo: 'MT309B', nombre: 'Análisis Numérico', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 15, codigo: 'FS329', nombre: 'Ondas', creditos: 4, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 16, codigo: 'ID212', nombre: 'Tech English I', creditos: 2, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },

  // Semestre 4
  { id: 17, codigo: 'SS462', nombre: 'Programación de Computadores III', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 18, codigo: 'SS463', nombre: 'Base de Datos', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 19, codigo: 'MT402', nombre: 'Ecuaciones Diferenciales', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 20, codigo: 'MT403', nombre: 'Estadística Descriptiva e Inferencial', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 21, codigo: 'FS400', nombre: 'Electromagnetismo', creditos: 4, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 22, codigo: 'ID341', nombre: 'Tech English II', creditos: 2, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },

  // Semestre 5
  { id: 23, codigo: 'SS500', nombre: 'Arquitectura de Computadores', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 24, codigo: 'SS501', nombre: 'Programación Web', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 25, codigo: 'SS502', nombre: 'Ingeniería de Software I', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 26, codigo: 'AI432', nombre: 'Investigación de Operaciones', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 27, codigo: 'ING301', nombre: 'Metodología de la Investigación', creditos: 2, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },

  // Semestre 6
  { id: 28, codigo: 'SS600', nombre: 'Sistemas Operativos', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 29, codigo: 'SS601', nombre: 'Modelos y Simulación', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 30, codigo: 'SS602', nombre: 'Ingeniería de Software II', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 31, codigo: 'SS603', nombre: 'Programación Móvil', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 32, codigo: 'SS604', nombre: 'Innovación y Emprendimiento Tecnológico', creditos: 2, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 2 },

  // Semestre 7
  { id: 33, codigo: 'SS701', nombre: 'Redes y Comunicaciones', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 34, codigo: 'SS702', nombre: 'Inteligencia Artificial', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 35, codigo: 'SS706', nombre: 'Ingeniería de Software III', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 36, codigo: 'SS707', nombre: 'Tecnologías Inmersivas', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 37, codigo: 'SS708', nombre: 'Research Project', creditos: 2, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 38, codigo: 'AI700', nombre: 'Ingeniería Económica', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },

  // Semestre 8
  { id: 39, codigo: 'SS802', nombre: 'Base de Datos Avanzadas', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 40, codigo: 'SS806', nombre: 'Seguridad de la Información', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 41, codigo: 'SS811', nombre: 'Ética Profesional', creditos: 2, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 42, codigo: 'SS812', nombre: 'Proyecto de Grado I', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },

  // Semestre 9
  { id: 43, codigo: 'SS912', nombre: 'Proyecto de Grado II', creditos: 3, semestreSugerido: 9, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 44, codigo: 'SS913', nombre: 'Electiva de Profundización I (Cloud & DevOps)', creditos: 3, semestreSugerido: 9, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 45, codigo: 'SS914', nombre: 'Electiva de Profundización II (Ciberseguridad Ofensiva)', creditos: 3, semestreSugerido: 9, programaId: 1, activa: true, cantidadGrupos: 2 },

  // Semestre 10
  { id: 46, codigo: 'SS1001', nombre: 'Práctica Empresarial y Pasantía', creditos: 6, semestreSugerido: 10, programaId: 1, activa: true, cantidadGrupos: 2 }
];

export const MOCK_GROUPS: Group[] = [
  // ==========================================
  // SEMESTRE 2
  // ==========================================

  // SS200 - Programación de Computadores I
  {
    id: 101,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 102,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 103,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 104,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'BRAULIO BARRIOS ZUÑIGA',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 105,
    numeroGrupo: '10-BANCO ING SISTEMAS',
    modalidad: 'VIRTUAL',
    sede: 'SEDE_BANCO',
    docente: 'NDOC (Docente por asignar)',
    aula: 'NREF',
    estado: 'ACTIVO',
    tieneDocenteAsignado: false,
    tieneRecursoFisicoAsignado: false,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '18:00', horaFin: '21:59', aula: 'NREF' },
    ]
  },

  // MT301B - Álgebra Lineal
  {
    id: 111,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JAIRO ENRIQUE MERCADO ARRIETA',
    aula: '101-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 7,
    materiaCodigo: 'MT301B',
    materiaNombre: 'Álgebra Lineal',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '101-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '101-CAMPUS' },
    ]
  },
  {
    id: 112,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JAIRO ENRIQUE MERCADO ARRIETA',
    aula: '102-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 7,
    materiaCodigo: 'MT301B',
    materiaNombre: 'Álgebra Lineal',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '102-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '102-CAMPUS' },
    ]
  },
  {
    id: 113,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ALVARO JOSE RANGEL OCHOA',
    aula: '101-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 7,
    materiaCodigo: 'MT301B',
    materiaNombre: 'Álgebra Lineal',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '101-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '101-CAMPUS' },
    ]
  },
  {
    id: 114,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ALVARO JOSE RANGEL OCHOA',
    aula: '102-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 7,
    materiaCodigo: 'MT301B',
    materiaNombre: 'Álgebra Lineal',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '16:00', horaFin: '17:59', aula: '102-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '16:00', horaFin: '17:59', aula: '102-CAMPUS' },
    ]
  },

  // MT303B - Cálculo Integral
  {
    id: 121,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LUIS RAMON CALDERON CUELLO',
    aula: '105-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 8,
    materiaCodigo: 'MT303B',
    materiaNombre: 'Cálculo Integral',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: '105-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: '105-CAMPUS' },
    ]
  },
  {
    id: 122,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LUIS RAMON CALDERON CUELLO',
    aula: '105-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 8,
    materiaCodigo: 'MT303B',
    materiaNombre: 'Cálculo Integral',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '105-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '105-CAMPUS' },
    ]
  },
  {
    id: 123,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EVERARDO DE JESUS PADILLA',
    aula: '106-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 8,
    materiaCodigo: 'MT303B',
    materiaNombre: 'Cálculo Integral',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '106-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '106-CAMPUS' },
    ]
  },
  {
    id: 124,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EVERARDO DE JESUS PADILLA',
    aula: '106-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 8,
    materiaCodigo: 'MT303B',
    materiaNombre: 'Cálculo Integral',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '106-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '106-CAMPUS' },
    ]
  },

  // FS202 - Mecánica
  {
    id: 131,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILFRIDO MANUEL ROJAS ROJAS',
    aula: 'LAB FISICA CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 9,
    materiaCodigo: 'FS202',
    materiaNombre: 'Mecánica',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB FISICA CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB FISICA CAMPUS' },
    ]
  },
  {
    id: 132,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILFRIDO MANUEL ROJAS ROJAS',
    aula: 'LAB FISICA CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 9,
    materiaCodigo: 'FS202',
    materiaNombre: 'Mecánica',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA CAMPUS' },
    ]
  },
  {
    id: 133,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS ARTURO MEDINA PEREZ',
    aula: 'LAB FISICA CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 9,
    materiaCodigo: 'FS202',
    materiaNombre: 'Mecánica',
    materiaCreditos: 4,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: 'LAB FISICA CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: 'LAB FISICA CAMPUS' },
    ]
  },

  // PG200 - Comunicación Oral y Escrita II
  {
    id: 141,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MARIA ELENA CASTRO OVIEDO',
    aula: '203-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 10,
    materiaCodigo: 'PG200',
    materiaNombre: 'Comunicación Oral y Escrita II',
    materiaCreditos: 2,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '08:00', horaFin: '09:59', aula: '203-CAMPUS' },
    ]
  },
  {
    id: 142,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MARIA ELENA CASTRO OVIEDO',
    aula: '203-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 10,
    materiaCodigo: 'PG200',
    materiaNombre: 'Comunicación Oral y Escrita II',
    materiaCreditos: 2,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'SABADO', horaInicio: '08:00', horaFin: '09:59', aula: '203-CAMPUS' },
    ]
  },
  {
    id: 143,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ROSA MARIA QUINTERO VEGA',
    aula: '204-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 10,
    materiaCodigo: 'PG200',
    materiaNombre: 'Comunicación Oral y Escrita II',
    materiaCreditos: 2,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '14:00', horaFin: '15:59', aula: '204-CAMPUS' },
    ]
  },

  // ==========================================
  // SEMESTRE 3
  // ==========================================

  // SS300 - Programación de Computadores II
  {
    id: 201,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'AMILKAR JOSE HERNANDEZ OÑATE',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 202,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PATRICIA ISABEL ALVAREZ ORTEGA',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 203,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ROBERTO AUGUSTO FERNANDEZ RAMIREZ',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 204,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ROBERTO AUGUSTO FERNANDEZ RAMIREZ',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '301-INFORMATICA' },
    ]
  },

  // SS301 - Estructura de Datos
  {
    id: 301,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 302,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ROBERTO ENRIQUE QUIROZ MOSCARELLA',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'VIERNES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 303,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'BRAULIO BARRIOS ZUÑIGA',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '402-SALA INTERNET' },
    ]
  },
  {
    id: 304,
    numeroGrupo: '05-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ADITH BISMARCK PEREZ OROZCO',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '12:00', horaFin: '13:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '12:00', horaFin: '13:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },

  // MT331 - Cálculo Multivariable
  {
    id: 311,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EDUARDO LUIS RIVERA OROZCO',
    aula: '107-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 13,
    materiaCodigo: 'MT331',
    materiaNombre: 'Cálculo Multivariable',
    materiaCreditos: 4,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '107-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '107-CAMPUS' },
    ]
  },
  {
    id: 312,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EDUARDO LUIS RIVERA OROZCO',
    aula: '107-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 13,
    materiaCodigo: 'MT331',
    materiaNombre: 'Cálculo Multivariable',
    materiaCreditos: 4,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: '107-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: '107-CAMPUS' },
    ]
  },
  {
    id: 313,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EDUARDO LUIS RIVERA OROZCO',
    aula: '108-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 13,
    materiaCodigo: 'MT331',
    materiaNombre: 'Cálculo Multivariable',
    materiaCreditos: 4,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '16:00', horaFin: '17:59', aula: '108-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '16:00', horaFin: '17:59', aula: '108-CAMPUS' },
    ]
  },

  // MT309B - Análisis Numérico
  {
    id: 321,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'GUILLERMO ALONSO ROJAS',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 14,
    materiaCodigo: 'MT309B',
    materiaNombre: 'Análisis Numérico',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 322,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'GUILLERMO ALONSO ROJAS',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 14,
    materiaCodigo: 'MT309B',
    materiaNombre: 'Análisis Numérico',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 323,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'GUILLERMO ALONSO ROJAS',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 14,
    materiaCodigo: 'MT309B',
    materiaNombre: 'Análisis Numérico',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '303-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '303-INFORMATICA' },
    ]
  },

  // FS329 - Ondas
  {
    id: 331,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOSE FRANCISCO CASTRO LOPEZ',
    aula: 'LAB FISICA II',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 15,
    materiaCodigo: 'FS329',
    materiaNombre: 'Ondas',
    materiaCreditos: 4,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB FISICA II' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB FISICA II' },
    ]
  },
  {
    id: 332,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOSE FRANCISCO CASTRO LOPEZ',
    aula: 'LAB FISICA II',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 15,
    materiaCodigo: 'FS329',
    materiaNombre: 'Ondas',
    materiaCreditos: 4,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA II' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA II' },
    ]
  },

  // ID212 - Tech English I
  {
    id: 341,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'KELLY JOHANA MARTINEZ DIAZ',
    aula: '205-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 16,
    materiaCodigo: 'ID212',
    materiaNombre: 'Tech English I',
    materiaCreditos: 2,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '08:00', horaFin: '09:59', aula: '205-CAMPUS' },
    ]
  },
  {
    id: 342,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'KELLY JOHANA MARTINEZ DIAZ',
    aula: '205-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 16,
    materiaCodigo: 'ID212',
    materiaNombre: 'Tech English I',
    materiaCreditos: 2,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '10:00', horaFin: '11:59', aula: '205-CAMPUS' },
    ]
  },

  // ==========================================
  // SEMESTRE 4
  // ==========================================

  // SS462 - Programación de Computadores III
  {
    id: 401,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ALFREDO DAVID BAUTISTA ROMERO',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 17,
    materiaCodigo: 'SS462',
    materiaNombre: 'Programación de Computadores III',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 402,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ALFREDO DAVID BAUTISTA ROMERO',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 17,
    materiaCodigo: 'SS462',
    materiaNombre: 'Programación de Computadores III',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 403,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOHN JAIRO PATIÑO VANEGAS',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 17,
    materiaCodigo: 'SS462',
    materiaNombre: 'Programación de Computadores III',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 404,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOHN JAIRO PATIÑO VANEGAS',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 17,
    materiaCodigo: 'SS462',
    materiaNombre: 'Programación de Computadores III',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '302-INFORMATICA' },
    ]
  },

  // SS463 - Base de Datos
  {
    id: 501,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'AMILKAR SIERRA ROMANO',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 18,
    materiaCodigo: 'SS463',
    materiaNombre: 'Base de Datos',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 502,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'AMILKAR SIERRA ROMANO',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 18,
    materiaCodigo: 'SS463',
    materiaNombre: 'Base de Datos',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 503,
    numeroGrupo: '07-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'YAIR ALFREDO VARGAS DELGADO',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 18,
    materiaCodigo: 'SS463',
    materiaNombre: 'Base de Datos',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '12:00', horaFin: '13:59', aula: '302-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '12:00', horaFin: '13:59', aula: '302-INFORMATICA' },
    ]
  },
  {
    id: 504,
    numeroGrupo: '08-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'YAIR ALFREDO VARGAS DELGADO',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 18,
    materiaCodigo: 'SS463',
    materiaNombre: 'Base de Datos',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '12:00', horaFin: '13:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '12:00', horaFin: '13:59', aula: '302-INFORMATICA' },
    ]
  },

  // MT402 - Ecuaciones Diferenciales
  {
    id: 411,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ORLANDO JOSE DE AVILA',
    aula: '103-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 19,
    materiaCodigo: 'MT402',
    materiaNombre: 'Ecuaciones Diferenciales',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '103-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '103-CAMPUS' },
    ]
  },
  {
    id: 412,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ORLANDO JOSE DE AVILA',
    aula: '103-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 19,
    materiaCodigo: 'MT402',
    materiaNombre: 'Ecuaciones Diferenciales',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '103-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '103-CAMPUS' },
    ]
  },

  // MT403 - Estadística Descriptiva e Inferencial
  {
    id: 421,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JAIME ENRIQUE DAZA DIAZ',
    aula: '104-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 20,
    materiaCodigo: 'MT403',
    materiaNombre: 'Estadística Descriptiva e Inferencial',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '104-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '104-CAMPUS' },
    ]
  },
  {
    id: 422,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JAIME ENRIQUE DAZA DIAZ',
    aula: '104-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 20,
    materiaCodigo: 'MT403',
    materiaNombre: 'Estadística Descriptiva e Inferencial',
    materiaCreditos: 3,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '104-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '104-CAMPUS' },
    ]
  },

  // FS400 - Electromagnetismo
  {
    id: 431,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOSE LUIS ROVIRA MEJIA',
    aula: 'LAB FISICA CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 21,
    materiaCodigo: 'FS400',
    materiaNombre: 'Electromagnetismo',
    materiaCreditos: 4,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: 'LAB FISICA CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: 'LAB FISICA CAMPUS' },
    ]
  },
  {
    id: 432,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOSE LUIS ROVIRA MEJIA',
    aula: 'LAB FISICA CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 21,
    materiaCodigo: 'FS400',
    materiaNombre: 'Electromagnetismo',
    materiaCreditos: 4,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: 'LAB FISICA CAMPUS' },
    ]
  },

  // ID341 - Tech English II
  {
    id: 441,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'KELLY JOHANA MARTINEZ DIAZ',
    aula: '205-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 22,
    materiaCodigo: 'ID341',
    materiaNombre: 'Tech English II',
    materiaCreditos: 2,
    semestreSugerido: 4,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '14:00', horaFin: '15:59', aula: '205-CAMPUS' },
    ]
  },

  // ==========================================
  // SEMESTRE 5
  // ==========================================

  // SS500 - Arquitectura de Computadores
  {
    id: 601,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MIGUEL ANGEL AROCA CERVANTES',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 23,
    materiaCodigo: 'SS500',
    materiaNombre: 'Arquitectura de Computadores',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '16:00', horaFin: '17:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '16:00', horaFin: '17:59', aula: '404-SALA INTERNET' },
    ]
  },
  {
    id: 602,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PABLO ANDRES GUERRA GONZALEZ',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 23,
    materiaCodigo: 'SS500',
    materiaNombre: 'Arquitectura de Computadores',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '403-SALA INTERNET' },
    ]
  },
  {
    id: 603,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MIGUEL ANGEL AROCA CERVANTES',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 23,
    materiaCodigo: 'SS500',
    materiaNombre: 'Arquitectura de Computadores',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '404-SALA INTERNET' },
    ]
  },

  // SS501 - Programación Web
  {
    id: 701,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'SADAINER FERNEY HERNANDEZ CHACON',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 702,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILMAN JOSE VEGA CASTILLA',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 703,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'SADAINER FERNEY HERNANDEZ CHACON',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 704,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILMAN JOSE VEGA CASTILLA',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '12:00', horaFin: '13:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '12:00', horaFin: '13:59', aula: '401-SALA INTERNET' },
    ]
  },

  // SS502 - Ingeniería de Software I
  {
    id: 801,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PATRICIA ISABEL ALVAREZ ORTEGA',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 25,
    materiaCodigo: 'SS502',
    materiaNombre: 'Ingeniería de Software I',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '401-SALA INTERNET' },
    ]
  },
  {
    id: 802,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JOHN JAIRO PATIÑO VANEGAS',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 25,
    materiaCodigo: 'SS502',
    materiaNombre: 'Ingeniería de Software I',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: '401-SALA INTERNET' },
    ]
  },
  {
    id: 803,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PATRICIA ISABEL ALVAREZ ORTEGA',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 25,
    materiaCodigo: 'SS502',
    materiaNombre: 'Ingeniería de Software I',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '302-INFORMATICA' },
    ]
  },

  // AI432 - Investigación de Operaciones
  {
    id: 811,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EDGAR ENRIQUE GOMEZ DIAZ',
    aula: '204-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 26,
    materiaCodigo: 'AI432',
    materiaNombre: 'Investigación de Operaciones',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '204-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '204-CAMPUS' },
    ]
  },
  {
    id: 812,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'EDGAR ENRIQUE GOMEZ DIAZ',
    aula: '204-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 26,
    materiaCodigo: 'AI432',
    materiaNombre: 'Investigación de Operaciones',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '204-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '204-CAMPUS' },
    ]
  },

  // ING301 - Metodología de la Investigación
  {
    id: 821,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LILIANA MARGARITA OÑATE DIAZ',
    aula: '108-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 27,
    materiaCodigo: 'ING301',
    materiaNombre: 'Metodología de la Investigación',
    materiaCreditos: 2,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '14:00', horaFin: '15:59', aula: '108-CAMPUS' },
    ]
  },
  {
    id: 822,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LILIANA MARGARITA OÑATE DIAZ',
    aula: '108-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 27,
    materiaCodigo: 'ING301',
    materiaNombre: 'Metodología de la Investigación',
    materiaCreditos: 2,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'SABADO', horaInicio: '08:00', horaFin: '09:59', aula: '108-CAMPUS' },
    ]
  },

  // ==========================================
  // SEMESTRE 6
  // ==========================================

  // SS600 - Sistemas Operativos
  {
    id: 901,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'OSWALDO RUEDA CARREÑO',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 28,
    materiaCodigo: 'SS600',
    materiaNombre: 'Sistemas Operativos',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '12:00', horaFin: '13:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '12:00', horaFin: '13:59', aula: '403-SALA INTERNET' },
    ]
  },
  {
    id: 902,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILLIAM ENRIQUE CASTRO CABARCAS',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 28,
    materiaCodigo: 'SS600',
    materiaNombre: 'Sistemas Operativos',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '403-SALA INTERNET' },
    ]
  },
  {
    id: 903,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'OSWALDO RUEDA CARREÑO',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 28,
    materiaCodigo: 'SS600',
    materiaNombre: 'Sistemas Operativos',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '403-SALA INTERNET' },
    ]
  },
  {
    id: 904,
    numeroGrupo: '05-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'OSWALDO RUEDA CARREÑO',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 28,
    materiaCodigo: 'SS600',
    materiaNombre: 'Sistemas Operativos',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '18:00', horaFin: '19:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '18:00', horaFin: '19:59', aula: '403-SALA INTERNET' },
    ]
  },

  // SS601 - Modelos y Simulación
  {
    id: 1001,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ANDRES RENE PERPIÑAN RTEYES',
    aula: 'LAB TECH I',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 29,
    materiaCodigo: 'SS601',
    materiaNombre: 'Modelos y Simulación',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '12:00', horaFin: '13:59', aula: 'LAB TECH I' },
      { diaSemana: 'MIERCOLES', horaInicio: '12:00', horaFin: '13:59', aula: 'LAB TECH I' },
    ]
  },
  {
    id: 1002,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ANDRES RENE PERPIÑAN RTEYES',
    aula: 'LAB TECH I',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 29,
    materiaCodigo: 'SS601',
    materiaNombre: 'Modelos y Simulación',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '12:00', horaFin: '13:59', aula: 'LAB TECH I' },
      { diaSemana: 'JUEVES', horaInicio: '12:00', horaFin: '13:59', aula: 'LAB TECH I' },
    ]
  },
  {
    id: 1003,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'ANDRES RENE PERPIÑAN RTEYES',
    aula: 'LAB TECH II',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 29,
    materiaCodigo: 'SS601',
    materiaNombre: 'Modelos y Simulación',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: 'LAB TECH II' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: 'LAB TECH II' },
    ]
  },

  // SS602 - Ingeniería de Software II
  {
    id: 1101,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MARIBEL ROMERO MESTRE',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 30,
    materiaCodigo: 'SS602',
    materiaNombre: 'Ingeniería de Software II',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '401-SALA INTERNET' },
    ]
  },
  {
    id: 1102,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MARIBEL ROMERO MESTRE',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 30,
    materiaCodigo: 'SS602',
    materiaNombre: 'Ingeniería de Software II',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '401-SALA INTERNET' },
    ]
  },
  {
    id: 1103,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'MARIBEL ROMERO MESTRE',
    aula: '401-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 30,
    materiaCodigo: 'SS602',
    materiaNombre: 'Ingeniería de Software II',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '401-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '401-SALA INTERNET' },
    ]
  },

  // SS603 - Programación Móvil
  {
    id: 1201,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'RONALD ALEXANDER VACCA ASCANIO',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 31,
    materiaCodigo: 'SS603',
    materiaNombre: 'Programación Móvil',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
    ]
  },
  {
    id: 1202,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'RONALD ALEXANDER VACCA ASCANIO',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 31,
    materiaCodigo: 'SS603',
    materiaNombre: 'Programación Móvil',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '302-INFORMATICA' },
    ]
  },
  {
    id: 1203,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'RONALD ALEXANDER VACCA ASCANIO',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 31,
    materiaCodigo: 'SS603',
    materiaNombre: 'Programación Móvil',
    materiaCreditos: 3,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: '302-INFORMATICA' },
    ]
  },

  // SS604 - Innovación y Emprendimiento Tecnológico
  {
    id: 1211,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS ALBERTO PLATA MONTERO',
    aula: '201-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 32,
    materiaCodigo: 'SS604',
    materiaNombre: 'Innovación y Emprendimiento Tecnológico',
    materiaCreditos: 2,
    semestreSugerido: 6,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '16:00', horaFin: '17:59', aula: '201-BLOQ I-INFORMATI' },
    ]
  },

  // ==========================================
  // SEMESTRE 7
  // ==========================================

  // SS701 - Redes y Comunicaciones
  {
    id: 1301,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILLIAM ENRIQUE CASTRO CABARCAS',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 33,
    materiaCodigo: 'SS701',
    materiaNombre: 'Redes y Comunicaciones',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '404-SALA INTERNET' },
    ]
  },
  {
    id: 1302,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'WILLIAM ENRIQUE CASTRO CABARCAS',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 33,
    materiaCodigo: 'SS701',
    materiaNombre: 'Redes y Comunicaciones',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: '403-SALA INTERNET' },
    ]
  },
  {
    id: 1303,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PABLO ANDRES GUERRA GONZALEZ',
    aula: '403-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 33,
    materiaCodigo: 'SS701',
    materiaNombre: 'Redes y Comunicaciones',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '18:00', horaFin: '19:59', aula: '403-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '18:00', horaFin: '19:59', aula: '403-SALA INTERNET' },
    ]
  },

  // SS702 - Inteligencia Artificial
  {
    id: 1401,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'TONNY ENRIQUE JIMENEZ MARQUEZ',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 34,
    materiaCodigo: 'SS702',
    materiaNombre: 'Inteligencia Artificial',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 1402,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'TONNY ENRIQUE JIMENEZ MARQUEZ',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 34,
    materiaCodigo: 'SS702',
    materiaNombre: 'Inteligencia Artificial',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
    ]
  },
  {
    id: 1403,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'TONNY ENRIQUE JIMENEZ MARQUEZ',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 34,
    materiaCodigo: 'SS702',
    materiaNombre: 'Inteligencia Artificial',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '12:00', horaFin: '13:59', aula: '303-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '12:00', horaFin: '13:59', aula: '303-INFORMATICA' },
    ]
  },

  // SS706 - Ingeniería de Software III
  {
    id: 1501,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JUAN ANDRES YANETH RINCON',
    aula: '402-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 35,
    materiaCodigo: 'SS706',
    materiaNombre: 'Ingeniería de Software III',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '402-SALA INTERNET' },
      { diaSemana: 'VIERNES', horaInicio: '10:00', horaFin: '11:59', aula: '402-SALA INTERNET' },
    ]
  },
  {
    id: 1502,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'JUAN ANDRES YANETH RINCON',
    aula: '402-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 35,
    materiaCodigo: 'SS706',
    materiaNombre: 'Ingeniería de Software III',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '402-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '402-SALA INTERNET' },
    ]
  },

  // SS707 - Tecnologías Inmersivas
  {
    id: 1601,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LUIS ALFREDO PEREZ PEREZ',
    aula: 'LAB TECH I',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 36,
    materiaCodigo: 'SS707',
    materiaNombre: 'Tecnologías Inmersivas',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: 'LAB TECH I' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: 'LAB TECH I' },
    ]
  },

  // SS708 - Research Project
  {
    id: 1701,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'NELSON ANIBAL FELIZZOLA DELGADO',
    aula: 'LAB TECH II',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 37,
    materiaCodigo: 'SS708',
    materiaNombre: 'Research Project',
    materiaCreditos: 2,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '18:00', horaFin: '19:59', aula: 'LAB TECH II' },
    ]
  },

  // AI700 - Ingeniería Económica
  {
    id: 1711,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS ALBERTO PLATA MONTERO',
    aula: '106-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 38,
    materiaCodigo: 'AI700',
    materiaNombre: 'Ingeniería Económica',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '106-CAMPUS' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '106-CAMPUS' },
    ]
  },
  {
    id: 1712,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS ALBERTO PLATA MONTERO',
    aula: '106-CAMPUS',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 38,
    materiaCodigo: 'AI700',
    materiaNombre: 'Ingeniería Económica',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '16:00', horaFin: '17:59', aula: '106-CAMPUS' },
      { diaSemana: 'JUEVES', horaInicio: '16:00', horaFin: '17:59', aula: '106-CAMPUS' },
    ]
  },

  // ==========================================
  // SEMESTRE 8, 9 Y 10
  // ==========================================

  // SS802 - Base de Datos Avanzadas
  {
    id: 1801,
    numeroGrupo: '01-VIRTUAL',
    modalidad: 'VIRTUAL',
    sede: 'CAMPUS',
    docente: 'NDOC (Docente por asignar)',
    aula: 'NREF',
    estado: 'ACTIVO',
    tieneDocenteAsignado: false,
    tieneRecursoFisicoAsignado: false,
    materiaId: 39,
    materiaCodigo: 'SS802',
    materiaNombre: 'Base de Datos Avanzadas',
    materiaCreditos: 3,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: 'NREF' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: 'NREF' },
    ]
  },
  {
    id: 1802,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'AMILKAR SIERRA ROMANO',
    aula: 'LAB TECH I',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 39,
    materiaCodigo: 'SS802',
    materiaNombre: 'Base de Datos Avanzadas',
    materiaCreditos: 3,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB TECH I' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: 'LAB TECH I' },
    ]
  },

  // SS806 - Seguridad de la Información
  {
    id: 1901,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PABLO ANDRES GUERRA GONZALEZ',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 40,
    materiaCodigo: 'SS806',
    materiaNombre: 'Seguridad de la Información',
    materiaCreditos: 3,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '18:00', horaFin: '19:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '18:00', horaFin: '19:59', aula: '404-SALA INTERNET' },
    ]
  },
  {
    id: 1902,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PABLO ANDRES GUERRA GONZALEZ',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 40,
    materiaCodigo: 'SS806',
    materiaNombre: 'Seguridad de la Información',
    materiaCreditos: 3,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '404-SALA INTERNET' },
    ]
  },

  // SS811 - Ética Profesional
  {
    id: 2001,
    numeroGrupo: '01-VIRTUAL',
    modalidad: 'VIRTUAL',
    sede: 'CAMPUS',
    docente: 'HECTOR FABIO HOYOS OCHOA',
    aula: 'CAMPUS VIRTUAL',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 41,
    materiaCodigo: 'SS811',
    materiaNombre: 'Ética Profesional',
    materiaCreditos: 2,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MIERCOLES', horaInicio: '12:00', horaFin: '13:59', aula: 'CAMPUS VIRTUAL' },
    ]
  },

  // SS812 - Proyecto de Grado I
  {
    id: 2101,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LILIANA MARGARITA OÑATE DIAZ',
    aula: 'LAB TECH I',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 42,
    materiaCodigo: 'SS812',
    materiaNombre: 'Proyecto de Grado I',
    materiaCreditos: 3,
    semestreSugerido: 8,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '06:00', horaFin: '07:59', aula: 'LAB TECH I' },
    ]
  },

  // SS912 - Proyecto de Grado II
  {
    id: 2201,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'LILIANA MARGARITA OÑATE DIAZ',
    aula: 'LAB TECH II',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 43,
    materiaCodigo: 'SS912',
    materiaNombre: 'Proyecto de Grado II',
    materiaCreditos: 3,
    semestreSugerido: 9,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '08:00', horaFin: '09:59', aula: 'LAB TECH II' },
    ]
  },

  // SS913 - Electiva de Profundización I
  {
    id: 2301,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'SADAINER FERNEY HERNANDEZ CHACON',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 44,
    materiaCodigo: 'SS913',
    materiaNombre: 'Electiva de Profundización I (Cloud & DevOps)',
    materiaCreditos: 3,
    semestreSugerido: 9,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
    ]
  },

  // SS914 - Electiva de Profundización II
  {
    id: 2401,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PABLO ANDRES GUERRA GONZALEZ',
    aula: '404-SALA INTERNET',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 45,
    materiaCodigo: 'SS914',
    materiaNombre: 'Electiva de Profundización II (Ciberseguridad Ofensiva)',
    materiaCreditos: 3,
    semestreSugerido: 9,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '16:00', horaFin: '17:59', aula: '404-SALA INTERNET' },
      { diaSemana: 'MIERCOLES', horaInicio: '16:00', horaFin: '17:59', aula: '404-SALA INTERNET' },
    ]
  },

  // SS1001 - Práctica Empresarial
  {
    id: 2501,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'COORDINADOR PRACTICAS UPC',
    aula: 'CONVENIO EMPRESARIAL',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 46,
    materiaCodigo: 'SS1001',
    materiaNombre: 'Práctica Empresarial y Pasantía',
    materiaCreditos: 6,
    semestreSugerido: 10,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'SABADO', horaInicio: '08:00', horaFin: '11:59', aula: 'SALA JUNTAS' },
    ]
  }
];

// Generador de respaldo de grupos en caso de que se agregue una nueva materia dinámicamente
export function getFallbackGroupsForSubject(sub: Subject): Group[] {
  const baseId = sub.id * 100;
  return [
    {
      id: baseId + 1,
      numeroGrupo: '01-CAMPUS',
      modalidad: 'PRESENCIAL',
      sede: 'CAMPUS',
      docente: 'DOCENTE ASIGNADO UPC',
      aula: '302-INFORMATICA',
      estado: 'ACTIVO',
      tieneDocenteAsignado: true,
      tieneRecursoFisicoAsignado: true,
      materiaId: sub.id,
      materiaCodigo: sub.codigo,
      materiaNombre: sub.nombre,
      materiaCreditos: sub.creditos,
      semestreSugerido: sub.semestreSugerido,
      periodoId: 1,
      periodoNombre: '2026-2',
      sesiones: [
        { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '302-INFORMATICA' },
        { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '302-INFORMATICA' },
      ]
    },
    {
      id: baseId + 2,
      numeroGrupo: '02-CAMPUS',
      modalidad: 'PRESENCIAL',
      sede: 'CAMPUS',
      docente: 'DOCENTE ASIGNADO UPC',
      aula: '303-INFORMATICA',
      estado: 'ACTIVO',
      tieneDocenteAsignado: true,
      tieneRecursoFisicoAsignado: true,
      materiaId: sub.id,
      materiaCodigo: sub.codigo,
      materiaNombre: sub.nombre,
      materiaCreditos: sub.creditos,
      semestreSugerido: sub.semestreSugerido,
      periodoId: 1,
      periodoNombre: '2026-2',
      sesiones: [
        { diaSemana: 'MARTES', horaInicio: '10:00', horaFin: '11:59', aula: '303-INFORMATICA' },
        { diaSemana: 'JUEVES', horaInicio: '10:00', horaFin: '11:59', aula: '303-INFORMATICA' },
      ]
    },
    {
      id: baseId + 3,
      numeroGrupo: '03-CAMPUS',
      modalidad: 'PRESENCIAL',
      sede: 'CAMPUS',
      docente: 'DOCENTE ASIGNADO UPC',
      aula: '401-SALA INTERNET',
      estado: 'ACTIVO',
      tieneDocenteAsignado: true,
      tieneRecursoFisicoAsignado: true,
      materiaId: sub.id,
      materiaCodigo: sub.codigo,
      materiaNombre: sub.nombre,
      materiaCreditos: sub.creditos,
      semestreSugerido: sub.semestreSugerido,
      periodoId: 1,
      periodoNombre: '2026-2',
      sesiones: [
        { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '401-SALA INTERNET' },
        { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '401-SALA INTERNET' },
      ]
    }
  ];
}
