import { Group, Period, Program, Subject, UserPreference } from '../types';

export const MOCK_PROGRAMS: Program[] = [
  {
    id: 1,
    codigo: 'ING-SISTEMAS',
    nombre: 'Ingeniería de Sistemas',
    universidad: 'Universidad Popular del Cesar',
    activo: true,
  }
];

export const MOCK_PERIODS: Period[] = [
  {
    id: 1,
    nombre: '2026-2',
    fechaInicio: '2026-08-03',
    fechaFin: '2026-12-15',
    activo: true,
  }
];

export const MOCK_SUBJECTS: Subject[] = [
  { id: 1, codigo: 'MT104', nombre: 'Cálculo Diferencial', creditos: 4, semestreSugerido: 1, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 2, codigo: 'MT117', nombre: 'Lógica Matemática', creditos: 3, semestreSugerido: 1, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 3, codigo: 'PG102', nombre: 'Comunicación Oral y Escrita I', creditos: 2, semestreSugerido: 1, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 4, codigo: 'SS105', nombre: 'Introducción a la Ingeniería de Sistemas', creditos: 2, semestreSugerido: 1, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 5, codigo: 'UPC01', nombre: 'Cátedra Upecista', creditos: 1, semestreSugerido: 1, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 6, codigo: 'SS200', nombre: 'Programación de Computadores I', creditos: 3, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 5 },
  { id: 7, codigo: 'MT301B', nombre: 'Álgebra Lineal', creditos: 3, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 8, codigo: 'MT303B', nombre: 'Cálculo Integral', creditos: 4, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 5 },
  { id: 9, codigo: 'FS202', nombre: 'Mecánica', creditos: 4, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 10, codigo: 'PG200', nombre: 'Comunicación Oral y Escrita II', creditos: 2, semestreSugerido: 2, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 11, codigo: 'SS300', nombre: 'Programación de Computadores II', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 12, codigo: 'SS301', nombre: 'Estructura de Datos', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 13, codigo: 'MT331', nombre: 'Cálculo Multivariable', creditos: 4, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 14, codigo: 'MT309B', nombre: 'Análisis Numérico', creditos: 3, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 15, codigo: 'FS329', nombre: 'Ondas', creditos: 4, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 16, codigo: 'ID212', nombre: 'Tech English I', creditos: 2, semestreSugerido: 3, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 17, codigo: 'SS462', nombre: 'Programación de Computadores III', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 18, codigo: 'SS463', nombre: 'Base de Datos', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 19, codigo: 'MT402', nombre: 'Ecuaciones Diferenciales', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 20, codigo: 'MT403', nombre: 'Estadística Descriptiva e Inferencial', creditos: 3, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 21, codigo: 'FS400', nombre: 'Electromagnetismo', creditos: 4, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 22, codigo: 'ID341', nombre: 'Tech English II', creditos: 2, semestreSugerido: 4, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 23, codigo: 'SS500', nombre: 'Arquitectura de Computadores', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 24, codigo: 'SS501', nombre: 'Programación Web', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 25, codigo: 'SS502', nombre: 'Ingeniería de Software I', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 26, codigo: 'AI432', nombre: 'Investigación de Operaciones', creditos: 3, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 27, codigo: 'ING301', nombre: 'Metodología de la Investigación', creditos: 2, semestreSugerido: 5, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 28, codigo: 'SS600', nombre: 'Sistemas Operativos', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 29, codigo: 'SS601', nombre: 'Modelos y Simulación', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 30, codigo: 'SS602', nombre: 'Ingeniería de Software II', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 4 },
  { id: 31, codigo: 'SS603', nombre: 'Programación Móvil', creditos: 3, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 32, codigo: 'SS604', nombre: 'Innovación y Emprendimiento Tecnológico', creditos: 2, semestreSugerido: 6, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 33, codigo: 'SS701', nombre: 'Redes y Comunicaciones', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 34, codigo: 'SS702', nombre: 'Inteligencia Artificial', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 35, codigo: 'SS706', nombre: 'Ingeniería de Software III', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 36, codigo: 'SS707', nombre: 'Tecnologías Inmersivas', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 37, codigo: 'SS708', nombre: 'Research Project', creditos: 2, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 38, codigo: 'AI700', nombre: 'Ingeniería Económica', creditos: 3, semestreSugerido: 7, programaId: 1, activa: true, cantidadGrupos: 3 },
  { id: 39, codigo: 'SS802', nombre: 'Base de Datos Avanzadas', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 40, codigo: 'SS806', nombre: 'Seguridad de la Información', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 41, codigo: 'SS811', nombre: 'Ética Profesional', creditos: 2, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
  { id: 42, codigo: 'SS812', nombre: 'Proyecto de Grado I', creditos: 3, semestreSugerido: 8, programaId: 1, activa: true, cantidadGrupos: 2 },
];

export const MOCK_GROUPS: Group[] = [
  // SS200 - Programación I
  {
    id: 101,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 102,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '10:00', horaFin: '11:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '10:00', horaFin: '11:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 103,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '08:00', horaFin: '09:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 104,
    numeroGrupo: '04-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'BRAULIO BARRIOS ZUÑIGA',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 105,
    numeroGrupo: '10-BANCO ING SISTEMAS',
    modalidad: 'VIRTUAL',
    sede: 'SEDE_BANCO',
    docente: 'NDOC',
    aula: 'NREF',
    estado: 'ACTIVO',
    tieneDocenteAsignado: false,
    tieneRecursoFisicoAsignado: false,
    materiaId: 6,
    materiaCodigo: 'SS200',
    materiaNombre: 'Programación de Computadores I',
    materiaCreditos: 3,
    semestreSugerido: 2,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'VIERNES', horaInicio: '18:00', horaFin: '21:59', aula: 'NREF' },
    ]
  },

  // SS300 - Programación II
  {
    id: 201,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'AMILKAR JOSE HERNANDEZ OÑATE',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 202,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'PATRICIA ISABEL ALVAREZ ORTEGA',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 11,
    materiaCodigo: 'SS300',
    materiaNombre: 'Programación de Computadores II',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '08:00', horaFin: '09:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '08:00', horaFin: '09:59', aula: '301-INFORMATICA' },
    ]
  },

  // SS301 - Estructura de Datos
  {
    id: 301,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'CARLOS EMILIANO OÑATE GOMEZ',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '202-BLOQ I-INFORMATI' },
    ]
  },
  {
    id: 303,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'BRAULIO BARRIOS ZUÑIGA',
    aula: '202-BLOQ I-INFORMATI',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 12,
    materiaCodigo: 'SS301',
    materiaNombre: 'Estructura de Datos',
    materiaCreditos: 3,
    semestreSugerido: 3,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '202-BLOQ I-INFORMATI' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '402-SALA INTERNET' },
    ]
  },

  // SS501 - Programación Web
  {
    id: 701,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'SADAINER FERNEY HERNANDEZ CHACON',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '18:00', horaFin: '19:59', aula: '301-INFORMATICA' },
    ]
  },
  {
    id: 703,
    numeroGrupo: '03-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'SADAINER FERNEY HERNANDEZ CHACON',
    aula: '301-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 24,
    materiaCodigo: 'SS501',
    materiaNombre: 'Programación Web',
    materiaCreditos: 3,
    semestreSugerido: 5,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '06:00', horaFin: '07:59', aula: '301-INFORMATICA' },
    ]
  },

  // SS702 - Inteligencia Artificial
  {
    id: 1401,
    numeroGrupo: '01-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'TONNY ENRIQUE JIMENEZ MARQUEZ',
    aula: '303-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 34,
    materiaCodigo: 'SS702',
    materiaNombre: 'Inteligencia Artificial',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'LUNES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
      { diaSemana: 'MIERCOLES', horaInicio: '14:00', horaFin: '15:59', aula: '303-INFORMATICA' },
    ]
  },
  {
    id: 1402,
    numeroGrupo: '02-CAMPUS',
    modalidad: 'PRESENCIAL',
    sede: 'CAMPUS',
    docente: 'TONNY ENRIQUE JIMENEZ MARQUEZ',
    aula: '302-INFORMATICA',
    estado: 'ACTIVO',
    tieneDocenteAsignado: true,
    tieneRecursoFisicoAsignado: true,
    materiaId: 34,
    materiaCodigo: 'SS702',
    materiaNombre: 'Inteligencia Artificial',
    materiaCreditos: 3,
    semestreSugerido: 7,
    periodoId: 1,
    periodoNombre: '2026-2',
    sesiones: [
      { diaSemana: 'MARTES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
      { diaSemana: 'JUEVES', horaInicio: '14:00', horaFin: '15:59', aula: '302-INFORMATICA' },
    ]
  }
];
